# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Gazettes Kenya
email: gazettes@codeforafrica.org
url: http://opengazettes.or.ng
jurisdiction: Kenya
jurisdiction_adjective: Kenyan
jurisdiction_code: KE
source_attribution: National Council for Law Reporting (Kenya Law)
source_attribution_link: http://kenyalaw.org/kl/
enforce_ssl: opengazettes.or.ke
baseurl:
description: Making Government Gazettes freely available.
twitter:
  username: code4africa

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  gazettes:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/banner_5.png

# Build settings
markdown: kramdown
exclude: [vendor]

google_analytics: UA-33350783-11

aleph_url: https://opengazettes.co
s3_url: https://archive.opengazettes.or.ke

